---
title: "Biodiversity patterns"
author: "Felix May"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Biodiversity patterns}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

#Generate landscape


```{r}
library(MoBspatial)
```


```{r,fig.width=5, fig.height=5}
pal1 <- gray(seq(0,1,len=6))
spec.lab <- expand.grid(sp.col=pal1, sp.pch=21:25,stringsAsFactors = F)

community1 <- Sim.Thomas.Community(S=nrow(spec.lab),N = 500,sigma = 0.05)
plot(Y~X, data=community1, pch=spec.lab$sp.pch[community1$SpecID], bg=spec.lab$sp.col[community1$SpecID],cex=1.2)
```

#Rank abundance curve

```{r,fig.width=5, fig.height=5}
abund <- sort(table(community1$SpecID),decreasing = T)
plot(as.numeric(abund), type="b", log="y", xlab="Species rank", ylab="Species abundance", pch=21, bg="gray")
```

#SAR and EAR

```{r, fig.width=5, fig.height=5}
SAR <- SAR.EAR.rand(community1, prop.A = c(0.01,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99,1)) 
plot(nspec.mean~Area, data=SAR, xlab="Area sampled", ylab="No. of species", pch=21, bg="black", ylim=c(0,length(abund)))
lines(nspec.mean~Area, data=SAR)
lines(nend.mean~Area, data=SAR,lty=2)
points(nend.mean~Area, data=SAR,pch=21,bg="gray")
legend("topleft",legend=c("SAR","EAR"),lty=c(1,2),pch=21,pt.bg=c("black","gray"),cex=1)
```

#Distance decay

```{r, fig.width=5, fig.height=5}
dd <- distance.decay(community1,prop.A = 0.05, nsamples = 30)
dd <- dd[order(dd$distance),]
plot(similarity~distance, data=dd, pch= 21, xlab="Distance", ylab="Jaccard similarity")
dd.loess <- loess(similarity~distance, data=dd)
pred.sim <- predict(dd.loess)
lines(dd$distance,pred.sim,lwd=2)
```

