// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rThomas_rcpp
DataFrame rThomas_rcpp(int nPoints, double sigma, double mu, double xmin, double xmax, double ymin, double ymax);
RcppExport SEXP MoBspatial_rThomas_rcpp(SEXP nPointsSEXP, SEXP sigmaSEXP, SEXP muSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nPoints(nPointsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    __result = Rcpp::wrap(rThomas_rcpp(nPoints, sigma, mu, xmin, xmax, ymin, ymax));
    return __result;
END_RCPP
}
// sSAC1_C
NumericVector sSAC1_C(NumericVector x, NumericVector y, IntegerVector id_spec);
RcppExport SEXP MoBspatial_sSAC1_C(SEXP xSEXP, SEXP ySEXP, SEXP id_specSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id_spec(id_specSEXP);
    __result = Rcpp::wrap(sSAC1_C(x, y, id_spec));
    return __result;
END_RCPP
}
