// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sSAC1_C
NumericVector sSAC1_C(NumericVector x, NumericVector y, IntegerVector id_spec);
RcppExport SEXP MoBspatial_sSAC1_C(SEXP xSEXP, SEXP ySEXP, SEXP id_specSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id_spec(id_specSEXP);
    rcpp_result_gen = Rcpp::wrap(sSAC1_C(x, y, id_spec));
    return rcpp_result_gen;
END_RCPP
}
// rThomas_rcpp
DataFrame rThomas_rcpp(int nPoints, int nMotherPoints, double sigma, double mu, double xmin, double xmax, double ymin, double ymax);
RcppExport SEXP MoBspatial_rThomas_rcpp(SEXP nPointsSEXP, SEXP nMotherPointsSEXP, SEXP sigmaSEXP, SEXP muSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nPoints(nPointsSEXP);
    Rcpp::traits::input_parameter< int >::type nMotherPoints(nMotherPointsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    rcpp_result_gen = Rcpp::wrap(rThomas_rcpp(nPoints, nMotherPoints, sigma, mu, xmin, xmax, ymin, ymax));
    return rcpp_result_gen;
END_RCPP
}
