# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rThomas_rcpp <- function(nPoints, sigma, mu, xmin = 0, xmax = 1, ymin = 0, ymax = 1) {
    .Call('MoBspatial_rThomas_rcpp', PACKAGE = 'MoBspatial', nPoints, sigma, mu, xmin, xmax, ymin, ymax)
}

sSAC1_C <- function(x, y, id_spec) {
    .Call('MoBspatial_sSAC1_C', PACKAGE = 'MoBspatial', x, y, id_spec)
}

